const DAYS=[
 {date:'2026-07-22',short:'Mié',title:'Llegada y Es Castell',summary:'Aterrizar, instalarse y empezar despacio junto al puerto de Maó.'},
 {date:'2026-07-23',short:'Jue',title:'Suroeste · Macarella',summary:'Sendero de miradores, calas turquesa y tarde en Ciutadella.'},
 {date:'2026-07-24',short:'Vie',title:'Sur central · Mitjana',summary:'Calas blancas, opción de Trebalúger y una tarde tranquila.'},
 {date:'2026-07-25',short:'Sáb',title:'Costa remota en kayak',summary:'Explorar la costa menos accesible desde Sant Tomàs.'},
 {date:'2026-07-26',short:'Dom',title:'Norte y Cavalleria',summary:'Pregonda, Fornells y un atardecer memorable en el faro.'},
 {date:'2026-07-27',short:'Lun',title:'Poniente e Ivette',summary:'Son Saura, Ciutadella y cena reservada frente a Cala Morell.'},
 {date:'2026-07-28',short:'Mar',title:'Levante y Favàritx',summary:'Paisaje lunar, calas salvajes y paseo por Maó.'},
 {date:'2026-07-29',short:'Mié',title:'Regreso',summary:'Desayuno, check-out y aeropuerto sin carreras.'}
];
const DEFAULT_PLANS=[
 {id:'p1',day:0,n:23,time:'15:30',name:'Barceló Hamilton · llegada',type:'Hotel',lat:39.8799,lng:4.2959,desc:'Check-in y descanso después del vuelo.'},
 {id:'p2',day:0,n:17,time:'18:00',name:'Es Castell y Cales Fonts',type:'Pueblo',lat:39.8777,lng:4.2891,desc:'Primer paseo a pie desde el hotel y cena por la zona.'},
 {id:'p3',day:1,n:21,time:'08:00',name:'Cala Galdana',type:'Ruta',lat:39.9380,lng:3.9600,desc:'Inicio de la ruta de miradores. Salida del hotel a las 07:15.'},
 {id:'p4',day:1,n:1,time:'09:00',name:'Macarella y Macarelleta',type:'Playa',lat:39.9373,lng:3.9357,desc:'Ruta a pie; llevar zapatillas, agua y picnic.'},
 {id:'p5',day:1,n:14,time:'18:00',name:'Ciutadella',type:'Pueblo',lat:40.0019,lng:3.8379,desc:'Casco antiguo, catedral, puerto y cena.'},
 {id:'p6',day:2,n:3,time:'08:15',name:'Mitjana y Mitjaneta',type:'Playa',lat:39.9356,lng:3.9717,desc:'Parking y 15–20 minutos a pie.'},
 {id:'p7',day:2,n:4,time:'11:30',name:'Trebalúger',type:'Ruta',lat:39.9277,lng:3.9923,desc:'Sólo si el calor y el grupo acompañan.'},
 {id:'p8',day:2,n:18,time:'18:00',name:'Es Mercadal',type:'Pueblo',lat:39.9886,lng:4.0938,desc:'Paseo y cena temprana al regreso.'},
 {id:'p9',day:3,n:22,time:'08:30',name:'Sant Tomàs · salida de kayak',type:'Reserva',lat:39.9146,lng:4.0440,desc:'Confirmar mar y política de cancelación.'},
 {id:'p10',day:3,n:6,time:'10:00',name:'Binigaus',type:'Playa',lat:39.9116,lng:4.0394,desc:'Primera parada de la costa remota.'},
 {id:'p11',day:3,n:7,time:'11:00',name:'Escorxada y Fustam',type:'Playa',lat:39.9166,lng:4.0088,desc:'Continuar sólo dentro del radio permitido por el alquiler.'},
 {id:'p12',day:4,n:10,time:'09:00',name:'Binimel·là y Pregonda',type:'Playa',lat:40.0573,lng:4.0403,desc:'35–50 min andando por sentido.'},
 {id:'p13',day:4,n:16,time:'17:00',name:'Fornells',type:'Pueblo',lat:40.0552,lng:4.1316,desc:'Paseo por el pueblo antes del atardecer.'},
 {id:'p14',day:4,n:9,time:'19:15',name:'Playa de Cavalleria',type:'Playa',lat:40.0720,lng:4.0862,desc:'Baño final si el mar está bien.'},
 {id:'p15',day:4,n:19,time:'20:15',name:'Faro de Cavalleria',type:'Ruta',lat:40.0884,lng:4.0920,desc:'Puesta de sol; llevar frontal.'},
 {id:'p16',day:5,n:5,time:'08:00',name:'Son Saura y Es Talaier',type:'Playa',lat:39.9271,lng:3.8940,desc:'Salir a las 07:00; el parking se llena pronto.'},
 {id:'p17',day:5,n:13,time:'15:30',name:'Cala en Brut',type:'Playa',lat:40.0066,lng:3.8050,desc:'Baño breve; saltar sólo con condiciones seguras.'},
 {id:'p18',day:5,n:14,time:'17:00',name:'Ciutadella',type:'Pueblo',lat:40.0019,lng:3.8379,desc:'Paseo antes de trasladarse a Cala Morell.'},
 {id:'p19',day:5,n:24,time:'20:00',name:'Ivette Beach Club',type:'Reserva',lat:40.0521,lng:3.8816,desc:'Cena reservada y atardecer en Cala Morell.'},
 {id:'p20',day:6,n:20,time:'09:30',name:'Faro de Favàritx',type:'Ruta',lat:39.9957,lng:4.2676,desc:'Acceso con bus L43 desde Maó; confirmar horarios.'},
 {id:'p21',day:6,n:12,time:'10:30',name:'Presili y Tortuga',type:'Playa',lat:39.9902,lng:4.2510,desc:'Elegir una o ambas según calor y hora de regreso.'},
 {id:'p22',day:6,n:15,time:'17:00',name:'Maó',type:'Pueblo',lat:39.8885,lng:4.2658,desc:'Casco histórico, mercado y puerto.'},
 {id:'p23',day:6,n:8,time:'19:00',name:'Es Caló Blanc y Binibèquer',type:'Playa',lat:39.8177,lng:4.2153,desc:'Extensión opcional; prescindir si el día ya ha sido largo.'},
 {id:'p24',day:7,n:23,time:'09:15',name:'Salida del hotel',type:'Hotel',lat:39.8799,lng:4.2959,desc:'Check-out, devolución del coche y vuelo a las 12:00.'}
];
const PACKING=['Zapatillas','Agua 1,5–2 L','Protector solar','Gorra','Bolsa estanca','Frontal','Batería externa','Picnic'];
const KEY='menorca-trip-v1';
function normalizeState(value){
 const safe=value&&typeof value==='object'?value:{};
 return {plans:Array.isArray(safe.plans)?safe.plans:DEFAULT_PLANS,selectedDay:Number.isInteger(safe.selectedDay)&&safe.selectedDay>=0&&safe.selectedDay<DAYS.length?safe.selectedDay:0,favorites:Array.isArray(safe.favorites)?safe.favorites:[],visited:Array.isArray(safe.visited)?safe.visited:[],notes:typeof safe.notes==='string'?safe.notes:'',packing:Array.isArray(safe.packing)?safe.packing:[]};
}
let storedState=null;try{storedState=JSON.parse(localStorage.getItem(KEY)||'null')}catch{localStorage.removeItem(KEY)}
let state=normalizeState(storedState);
let map,markers=[],streetLayer,illustratedLayer,deferredPrompt;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function mapsUrl(p){return `https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}&travelmode=driving`}
function updateCountdown(){const now=new Date(),start=new Date('2026-07-22T00:00:00+02:00'),end=new Date('2026-07-30T00:00:00+02:00');let label='Próximo viaje',num=Math.ceil((start-now)/86400000);if(now>=start&&now<end){label='Viaje en curso';num=Math.max(0,Math.ceil((end-now)/86400000));$('#heroText').textContent='Tu itinerario está listo. Ajusta el día según el viento y las ganas.'}else if(now>=end){label='Recuerdos de Menorca';num=0}$('#tripStatus').textContent=label;$('#countdownDays').textContent=Math.max(0,num)}
function renderDays(){const box=$('#dayStrip');box.innerHTML=DAYS.map((d,i)=>`<button class="day-chip ${i===state.selectedDay?'active':''}" data-day="${i}" role="tab"><b>${d.short}</b><span>${new Date(d.date+'T12:00').getDate()}</span></button>`).join('');$$('.day-chip').forEach(b=>b.onclick=()=>{state.selectedDay=+b.dataset.day;save()});const d=DAYS[state.selectedDay],daily=state.plans.filter(p=>p.day===state.selectedDay),done=daily.filter(p=>state.visited.includes(p.id)).length,pct=daily.length?Math.round(done/daily.length*100):0;$('#daySummary').innerHTML=`<h3>${d.title}</h3><p>${d.summary}</p><div class="progress-row"><div class="progress-track"><span style="width:${pct}%"></span></div><small>${done} de ${daily.length} hechas</small></div>`}
function planCard(p){const fav=state.favorites.includes(p.id),done=state.visited.includes(p.id),directions=p.lat&&p.lng?`<a href="${mapsUrl(p)}" target="_blank" rel="noopener">Cómo llegar ↗</a>`:'';return `<article class="plan-card ${done?'visited':''}" data-plan-id="${p.id}"><div class="plan-number">${p.n||'•'}</div><div><span class="plan-time">${p.time||'Sin hora'} · ${p.type}</span><h3>${p.name}</h3><p>${p.desc||''}</p></div><label class="complete-toggle"><input class="done-check" type="checkbox" data-id="${p.id}" ${done?'checked':''}><span>${done?'Actividad completada':'Marcar actividad como hecha'}</span></label><div class="card-links">${directions}<button class="edit" data-id="${p.id}">Editar</button><button class="remove" data-id="${p.id}">Quitar</button><button class="fav" data-id="${p.id}" aria-label="Favorito">${fav?'♥ Favorito':'♡ Guardar'}</button></div></article>`}
function bindCards(){ $$('.fav').forEach(b=>b.onclick=()=>toggleArray('favorites',b.dataset.id));$$('.done-check').forEach(b=>b.onchange=()=>{toggleArray('visited',b.dataset.id);toast(b.checked?'Actividad completada':'Actividad pendiente')});$$('.edit').forEach(b=>b.onclick=()=>openEdit(b.dataset.id));$$('.remove').forEach(b=>b.onclick=()=>{if(confirm('¿Quitar este plan del itinerario?')){state.plans=state.plans.filter(p=>p.id!==b.dataset.id);state.visited=state.visited.filter(id=>id!==b.dataset.id);state.favorites=state.favorites.filter(id=>id!==b.dataset.id);save();toast('Plan eliminado')}})}
function toggleArray(k,id){state[k]=state[k].includes(id)?state[k].filter(x=>x!==id):[...state[k],id];save()}
function renderPlans(){const plans=state.plans.filter(p=>p.day===state.selectedDay).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'));$('#planList').innerHTML=plans.length?plans.map(planCard).join(''):'<div class="info-card"><p>No hay planes. Añade uno y construye este día a tu manera.</p></div>';bindCards()}
function renderSaved(){const favs=state.plans.filter(p=>state.favorites.includes(p.id));$('#statsGrid').innerHTML=`<div class="stat"><strong>${state.plans.length}</strong><small>planes</small></div><div class="stat"><strong>${state.visited.length}</strong><small>visitados</small></div><div class="stat"><strong>${favs.length}</strong><small>favoritos</small></div>`;$('#favoritesList').innerHTML=favs.length?favs.map(p=>`<div class="compact-item"><span><b>${p.n||'•'} · ${p.name}</b><br><small>${DAYS[p.day].short} ${new Date(DAYS[p.day].date+'T12:00').getDate()}</small></span><a href="${mapsUrl(p)}" target="_blank">⌖</a></div>`).join(''):'<div class="info-card"><p>Marca lugares con ♡ para encontrarlos aquí.</p></div>';$('#tripNotes').value=state.notes}
function renderPacking(){ $('#packingList').innerHTML=PACKING.map((x,i)=>`<label class="pack-item"><input type="checkbox" data-pack="${i}" ${state.packing.includes(i)?'checked':''}> ${x}</label>`).join('');$$('[data-pack]').forEach(c=>c.onchange=()=>{const i=+c.dataset.pack;state.packing=c.checked?[...new Set([...state.packing,i])]:state.packing.filter(x=>x!==i);localStorage.setItem(KEY,JSON.stringify(state))})}
function initMap(){if(map||!window.L)return;map=L.map('map',{zoomControl:false,attributionControl:false,minZoom:9}).setView([39.97,4.10],10);streetLayer=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'});illustratedLayer=L.imageOverlay('assets/menorca-ilustrada.png',[[39.663,3.688],[40.206,4.454]],{opacity:1,interactive:false}).addTo(map);L.control.zoom({position:'topright'}).addTo(map);renderMap()}
function setMapMode(mode){if(!map)initMap();if(mode==='street'){map.removeLayer(illustratedLayer);streetLayer.addTo(map)}else{map.removeLayer(streetLayer);illustratedLayer.addTo(map)}$$('[data-map-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mapMode===mode));map.setView([39.97,4.10],10);setTimeout(()=>map.invalidateSize(),60)}
function renderMap(){const unique=new Map();state.plans.filter(p=>p.lat&&p.lng).forEach(p=>unique.set(`${p.lat},${p.lng}`,p));const items=[...unique.values()];$('#locationCount').textContent=`${items.length} lugares`;if(!map)return;markers.forEach(m=>m.remove());markers=[];items.forEach(p=>{const icon=L.divIcon({className:'',html:`<div style="width:30px;height:30px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:${state.visited.includes(p.id)?'#5b8c65':'#0d6872'};border:3px solid white;box-shadow:0 4px 10px #0004"><b style="display:grid;place-items:center;height:100%;color:white;transform:rotate(45deg);font-size:11px">${p.n||'•'}</b></div>`,iconSize:[30,30],iconAnchor:[15,30]});markers.push(L.marker([p.lat,p.lng],{icon}).addTo(map).bindPopup(`<b>${p.name}</b><br>${DAYS[p.day].short} · ${p.time||''}<br><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Abrir en Google Maps</a>`))});$('#mapResults').innerHTML=items.slice(0,10).map(p=>`<button class="map-result" data-lat="${p.lat}" data-lng="${p.lng}"><b>${p.n||'•'} · ${p.name}</b><small>${DAYS[p.day].title}</small></button>`).join('');$$('.map-result').forEach(b=>b.onclick=()=>map.flyTo([+b.dataset.lat,+b.dataset.lng],13))}
function fillDaySelect(){ $('#planDay').innerHTML=DAYS.map((d,i)=>`<option value="${i}">${d.short} ${new Date(d.date+'T12:00').getDate()} · ${d.title}</option>`).join('')}
function openEdit(id){const p=state.plans.find(x=>x.id===id);$('#modalTitle').textContent=p?'Editar plan':'Añadir un plan';$('#editId').value=p?.id||'';$('#planDay').value=p?.day??state.selectedDay;$('#planName').value=p?.name||'';$('#planTime').value=p?.time||'';$('#planType').value=p?.type||'Playa';$('#planDescription').value=p?.desc||'';$('#planLat').value=p?.lat||'';$('#planLng').value=p?.lng||'';$('#planModal').showModal()}
function renderAll(){renderDays();renderPlans();renderSaved();renderPacking();renderMap()}
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));if(b.dataset.view==='mapView'){initMap();setTimeout(()=>map.invalidateSize(),80)}});
$$('[data-map-mode]').forEach(b=>b.onclick=()=>setMapMode(b.dataset.mapMode));
$$('[data-open="planModal"]').forEach(b=>b.onclick=()=>openEdit());
$('#planForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#editId').value||`custom-${Date.now()}`;const old=state.plans.find(p=>p.id===id);const p={id,day:+$('#planDay').value,n:old?.n||null,time:$('#planTime').value,name:$('#planName').value.trim(),type:$('#planType').value,desc:$('#planDescription').value.trim(),lat:+$('#planLat').value||null,lng:+$('#planLng').value||null};state.plans=old?state.plans.map(x=>x.id===id?p:x):[...state.plans,p];state.selectedDay=p.day;$('#planModal').close();save();toast('Plan guardado')});
$('#tripNotes').addEventListener('input',e=>{state.notes=e.target.value;localStorage.setItem(KEY,JSON.stringify(state))});
$('#locateBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(pos=>{map.setView([pos.coords.latitude,pos.coords.longitude],14);L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:8,color:'#fff',weight:3,fillColor:'#d9634e',fillOpacity:1}).addTo(map).bindPopup('Estás aquí').openPopup()},()=>toast('No se pudo obtener tu ubicación'));
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='menorca-mi-viaje.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const imported=JSON.parse(r.result);if(!imported||!Array.isArray(imported.plans))throw new Error();state=normalizeState(imported);save();toast('Copia restaurada')}catch{toast('El archivo no es válido')}finally{e.target.value=''}};r.readAsText(f)};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
fillDaySelect();updateCountdown();renderAll();
